package inventariovehiculos;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class AgregarCarros extends javax.swing.JFrame {
    private ResultSet resultadoMarca,resultadoModelo,resultadoColor,resultadoMotor,resultadoTipo,resultadoCombustible;
    private String valor,color,IdMarca,IdModelo,IdColor,IdCombustible,numero,IdMotor,IdTipo,correlativo,completo,first;
    private int posicion,cuantos;
    private boolean encontrado=false;
    private char primerNumero,segundoNumero;
    private DefaultComboBoxModel marcas=new DefaultComboBoxModel();
    private DefaultComboBoxModel colores=new DefaultComboBoxModel();
    private DefaultComboBoxModel motores=new DefaultComboBoxModel();
    private DefaultComboBoxModel tipos=new DefaultComboBoxModel();
    private DefaultComboBoxModel combustibles=new DefaultComboBoxModel();
    private Tablas conexion=new Tablas();
public AgregarCarros() {
        initComponents();
        this.setLocationRelativeTo(null);
        cmbMarca.setModel(marcas);
        cmbColor.setModel(colores);
        cmbCombustibles.setModel(combustibles);
        cmbMotor.setModel(motores);
        cmbTipo.setModel(tipos);
        resultadoMarca=conexion.buscarMarcas();
        resultadoColor=conexion.buscarColores();
        resultadoCombustible=conexion.buscarCombustibles();
        resultadoMotor=conexion.buscarMotores();
        resultadoTipo=conexion.buscarTipos();
        Llenar();
    }
     public void Llenar(){
            try{
            marcas.addElement("<Seleccione>");
            colores.addElement("<Seleccione>");
            combustibles.addElement("<Seleccione>");
            motores.addElement("<Seleccione>");
            tipos.addElement("<Seleccione>");
            while(resultadoMarca.next()){
                marcas.addElement(resultadoMarca.getString(1));
            }
            while(resultadoColor.next()){
                colores.addElement(resultadoColor.getString(1));
            }
            while(resultadoCombustible.next()){
                combustibles.addElement(resultadoCombustible.getString(1));
            }
            while(resultadoMotor.next()){
                motores.addElement(resultadoMotor.getString(1));
            }
            while(resultadoTipo.next()){
                tipos.addElement(resultadoTipo.getString(1));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error: "+ e.getMessage());
        }
        }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        cmbMotor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbCombustibles = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        cmbMarca = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Modelo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 22, -1, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 19, 110, -1));

        jLabel3.setText("Marca");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 21, -1, -1));

        jLabel4.setText("Color");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 101, -1, -1));

        getContentPane().add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 97, 130, -1));

        getContentPane().add(cmbMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 137, 130, -1));

        jLabel5.setText("Motor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 141, -1, -1));

        jLabel6.setText("Tipo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 141, -1, -1));

        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 137, 110, -1));

        jLabel7.setText("Combustible");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 101, -1, -1));

        getContentPane().add(cmbCombustibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 97, 110, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 212, -1, -1));

        jLabel9.setText("Cantidad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 189, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 186, 57, -1));

        jLabel10.setText("Precio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 189, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 186, 57, -1));

        jLabel11.setText("Version");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 60, -1, -1));
        getContentPane().add(txtVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 126, -1));

        getContentPane().add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 126, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("MG16068");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        encontrado=false;
        if(cmbMarca.getSelectedItem().equals("<Seleccione>")){
            JOptionPane.showMessageDialog(null,"Seleecione una marca ");
            cmbMarca.requestFocus();
        }else if(cmbColor.getSelectedItem().equals("<Seleccione>")){
            JOptionPane.showMessageDialog(null,"Seleccione un color");
            cmbColor.requestFocus();
        }else if(cmbCombustibles.getSelectedItem().equals("<Seleccione>")){
            JOptionPane.showMessageDialog(null,"Seleccione un combustible");
            cmbCombustibles.requestFocus();
        }else if(cmbMotor.getSelectedItem().equals("<Seleccione>")){
        JOptionPane.showMessageDialog(null,"Seleccione un motor");
        cmbMotor.requestFocus();
        }else if(cmbTipo.getSelectedItem().equals("<Seleccione>")){
            JOptionPane.showMessageDialog(null,"Seleccione un tipo");
            cmbTipo.requestFocus();
        }else if(txtModelo.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese un modelo");
            txtModelo.requestFocus();
        }else if(txtVersion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese  una version");
            txtVersion.requestFocus();
        }else if(txtCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese cantidad");
            txtCantidad.requestFocus();
        }else if(txtPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese precio");
            txtPrecio.requestFocus();
        }
        IdMarca=("0"+(cmbMarca.getSelectedIndex()));
        IdColor="0"+cmbColor.getSelectedIndex();
        IdCombustible="0"+cmbCombustibles.getSelectedIndex();
        IdMotor="0"+cmbMotor.getSelectedIndex();
        IdTipo="0"+cmbTipo.getSelectedIndex();
        resultadoModelo=conexion.BuscarModelo(IdMarca, txtModelo.getText());
        try{
           
            while(resultadoModelo.next()){  
                correlativo=resultadoModelo.getString(1);
                primerNumero=correlativo.charAt(2);
                segundoNumero=correlativo.charAt(3);
                completo=""+primerNumero+segundoNumero;
                IdModelo=IdMarca+completo;
                encontrado=true;
            }
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
        if(encontrado==false){
            resultadoModelo=conexion.MayorIdModelo(IdMarca);
        try{
            while(resultadoModelo.next()){
                if(resultadoModelo.getInt(1)==0){
                primerNumero='0';
                segundoNumero='0';    
                }else if(resultadoModelo.getInt(1)>100){
                    correlativo=resultadoModelo.getString(1);
                    primerNumero=correlativo.charAt(1);
                    segundoNumero=correlativo.charAt(2);
                }else if(resultadoModelo.getInt(1)>1000){
                    correlativo=resultadoModelo.getString(1);
                    primerNumero=correlativo.charAt(2);
                    segundoNumero=correlativo.charAt(3);
                }if(segundoNumero==9){
                    first=""+primerNumero;
                    int h=(Integer.parseInt(first))+1;
                    segundoNumero='0';
                    completo=""+h+segundoNumero;
                    IdModelo=IdMarca+completo;
                }else{
                    numero=""+segundoNumero;
                    int numFinal=(Integer.parseInt(numero))+1;
                    completo=""+primerNumero+numFinal;
                    IdModelo=IdMarca+completo;
                }
            }
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
        }
        conexion.insertarModelo(IdMarca, IdModelo, txtModelo.getText(), IdColor, IdCombustible, IdMotor, IdTipo, txtCantidad.getText(), txtPrecio.getText(),txtVersion.getText() );
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbCombustibles;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbMotor;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
